### ISSUE TITLE
This is actually a request

### ISSUE THREAD

**Issue by VandrerenErik** [protonmail-desktop/application#631] opened 2020-08-21 00:58 UTC
The only thing stopping me from using this wonderful app is the lack of my password manager extension. Since this is an electron app it would be nice to have password manager like Bitwarden included. Having to write login in all of my accounts everytime the app repoens is a little bit of a pain. In the browser I have it easy with Bitwarden.

**Comment by kontrollanten** [comment] 2020-08-21 07:53
Thanks @VandrerenErik ! I think this is duplicate of #90 I'll close this issue, subscribe to #90 to keep updated.

**Closed by kontrollanten** 2020-08-21 07:53 UTC

**Comment by VandrerenErik** [comment] 2020-08-21 08:10
Similar but not the same and you looped both issues and closed both of them using the other as excuse...
